changelog:
  exclude:
    labels:
      - 'for-release'
      - 'ignore-in-release'

  categories:
    - title: 'Bug Fix'
      labels:
        - 'bug'
    - title: 'Other'
      labels:
        - '*'