

package com.example.plugin.test.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.TestMetadata;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/**
 * This class is generated by {@link com.example.plugin.test.GenerateTestsKt}. DO NOT MODIFY MANUALLY
 */
@SuppressWarnings("all")
@TestMetadata("src/testData/codegen")
@TestDataPath("$PROJECT_ROOT")
public class CodeGenTestRunnerGenerated extends AbstractCodeGenTestRunner {
    @Test
    public void testAllFilesPresentInCodegen() {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/testData/codegen"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("genericAnnotationIssue.kt")
    public void testGenericAnnotationIssue() {
        runTest("src/testData/codegen/genericAnnotationIssue.kt");
    }
}
