name: build and publish release
on:
  push:
    tags:
      - v**
  # 手动触发工作流
  workflow_dispatch:

env:
  GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
  GPG_SECRET_KEY: ${{ secrets.GPG_PRI_KEY }}
  GPG_PASSWORD: ${{ secrets.GPG_PASSWORD }}
  OSSRH_USER: ${{ secrets.OSS_USERNAME }}
  OSSRH_PASSWORD: ${{ secrets.OSS_PASSWORD }}
  RELEASE: true
  CI: true
  IS_CI: true
  GRADLE_OPTS: "-Xmx8G -XX:MaxPermSize=2G -Dfile.encoding=UTF-8"

jobs:
  test-build-publish:
    name: Test and build
#    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      # 检出仓库代码
      - name: Check out repo
        uses: actions/checkout@v3

      # Setup java
      # https://github.com/marketplace/actions/setup-java-jdk
      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Test and publish to sonatype
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6
          arguments: |
            assemble 
            allTests
            build
            publishToSonatype
            closeAndReleaseStagingRepository
            --info
            --warning-mode all
            -x test
            --build-cache
            -Porg.gradle.jvmargs="-XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8"
            -Porg.gradle.workers.max=8
            

  publish-gradle-plugin:
    name: Publish Gradle Plugin
    runs-on: ubuntu-latest
    needs: test-build-publish
    steps:
      # 检出仓库代码
      - name: Check out repo
        uses: actions/checkout@v3

      # Setup java
      # https://github.com/marketplace/actions/setup-java-jdk
      - name: Setup Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Publish to sonatype
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6
          arguments: |
            build
            publishPlugins
            --info
            --warning-mode all
            -x test
            --build-cache
            -Porg.gradle.jvmargs="-XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8"
            -Porg.gradle.workers.max=8
            -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} 
            -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}
  

  create-release:
    name: Create release
    runs-on: ubuntu-latest
    needs: [test-build-publish, publish-gradle-plugin]
    permissions:
      contents: write
    steps:
        # Create gitHub release
      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.FORTE_TOKEN }}
#          body_path: .changelog/${{ github.ref_name }}.md
          generate_release_notes: true
          prerelease: ${{ contains(github.ref_name, 'preview') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'alpha') }}
