name: Test Branch
on:
  pull_request:
    branches:
      - 'dev'
    paths:
      - '**.java'
      - '**.kt'
      - '**.kts'
      - '*/src/*/kotlin/**'
      - '*/src/*/java/**'
      - '*/src/*/resource/**'
      - 'gradle/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  IS_CI: true
  GRADLE_OPTS: "-Dfile.encoding=UTF-8"
  GRADLE_VERSION: 8.10.2

jobs:
  build-test:
    name: Build and test
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 11
          cache: 'gradle'

      - name: Run All Tests
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}
          arguments: |
            assemble
            build
            test
            --info 
            --warning-mode all
#            --build-cache
#            -Porg.gradle.daemon=false
#            -Porg.gradle.jvmargs="-Xmx4g -Xms2g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8"

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: test-reports-${{ matrix.os }}
          path: '**/build/reports/tests'
          retention-days: 7
