name: Test Branch
on:
  pull_request:
    branches:
      - 'dev'
    paths:
      - '**.java'
      - '**.kt'
      - '**.kts'
      - '*/src/*/kotlin/**'
      - '*/src/*/java/**'
      - '*/src/*/resource/**'
      - 'gradle/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  JAVA_VERSION: 11
  JAVA_DISTRIBUTION: zulu
  GRADLE_VERSION: 8.10.2
  IS_CI: true
  GRADLE_OPTS: "-Dfile.encoding=UTF-8"

jobs:
  build-test:
    name: Build and test
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}

      - name: Run All Tests
        run: gradle assemble build test -s --warning-mode all
        env:
          ORG_GRADLE_PROJECT_org.gradle.jvmargs: "-XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8"

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports-${{ runner.os }}
          path: '**/build/reports/tests'
          retention-days: 7
